import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <header>
          {/* Tu header fijo: logo, menú, etc. */}
          <h1>Ejemplo de header</h1>
        </header>

        <main>
          {children} {/* Aquí se renderiza el contenido de cada página */}
        </main>

        <footer>
          {/* Tu footer fijo */}
          <p>Ejemplo de footer</p>
        </footer>
      </body>
    </html>
  )
}
